server {
    listen 80;

    location / {
        root   /usr/share/nginx/html;
        index  index.html;
        # Essencial para que o React Router (client-side routing) funcione.
        # Se uma rota como /livros não for encontrada, ele serve o index.html.
        try_files $uri $uri/ /index.html;
    }
}