server {
    # O Nginx escutará na porta 80 dentro do contêiner
    listen 80;

    # Localização dos arquivos estáticos do React (o resultado do `npm run build`)
    location / {
        root   /usr/share/nginx/html;
        index  index.html;
        # Essencial para que o React Router (client-side routing) funcione.
        # Se uma rota como /livros não for encontrada, ele serve o index.html.
        try_files $uri $uri/ /index.html;
    }

    # Redirecionamento (Proxy Reverso) para a API
    location /api/ {
        # Remove o prefixo /api da URL antes de enviar para o backend
        rewrite /api/(.*) /$1 break;

        # Redireciona a chamada para o serviço 'backend' na porta 3333
        # (comunicação interna da rede Docker)
        proxy_pass http://backend:3333;
    }
}